### ISSUE TITLE
OneFlow nn.Linear权重载入问题

### ISSUE THREAD

**Issue by rentainhe** [Oneflow-Inc/models#133]
本次issue的背景是，在复现mlp-mixer的时候，搭建了和pytorch一样的模型，载入了一样的权重，结果精度为0，通过逐层比较载入后的权重的值发现，在中间的linear层所载入的值和pytorch相反，像是transpose后的值

debug的代码已经提交了相应的draft PR 可以复现：https://github.com/Oneflow-Inc/models/pull/132

相应使用的pytorch权重下载链接：https://oneflow-public.oss-cn-beijing.aliyuncs.com/model_zoo/mlp_mixer/mixer_b16_224.pth

## pre-requiresite
```
pip install pytorch
pip install timm
```

在compare.py下，比较方法如下：
- 构建pytorch的mlp-mixer模型，并载入权重后导出state_dict
```python
def torch_weight_load(model, checkpoint_path):
    state_dict = torch.load(checkpoint_path)
    model.load_state_dict(state_dict)
    return model.state_dict()
```
- 构建oneflow模型，并转换pytorch的权重载入后导出state_dict
```python
def oneflow_weight_load(model, checkpoint_path):
    state_dict = torch.load(checkpoint_path)
    new_parameters = dict()
    for key, value in state_dict.items():
        if "num_batches_tracked" not in key:
            val = value.detach().cpu().numpy()
            new_parameters[key] = val.astype(np.float32)
    model.load_state_dict(new_parameters)
    return model.state_dict()
```
- 逐层比较weight的值，打印不一致的key
```python
def compare(torch_dict, of_dict):
    for torch_key, of_key in zip(torch_dict, of_dict):
        value = torch_dict[torch_key].numpy() - of_dict[of_key].numpy()
        if value.mean() != 0.0:
            print(torch_key)
```
通过打印的结果发现在中间的linear层都不一致:
![J5`B2MV7HEH422UF__C9V S](https://user-images.githubusercontent.com/48727989/130796668-58c06b3b-e62b-4c87-b6d0-30c9d7a22af0.png)

发现了以下问题：
- 中间层的linear权重都不一致
- patch_embed的卷积层权重也不一致？
- 最后一层的head输出是一致的？？（最后一层head也是一层linear）

可能的原因：
- 我compare代码写错了（可能性比较小因为载入权重的模型我验证过了，结果和pytorch完全不一致，输入变量都控制了，pytorch的结果为69，oneflow为0，权重载入出问题）
- 之前vit中也有类似的问题，当时的解决办法是在linear载入的时候加入转置
- linear层的权重载入可能和torch是反的，需要注意一下转置问题

**Comment by daquexian** [comment]
在 https://github.com/Oneflow-Inc/oneflow/pull/6117 里修复，待合并
