### ISSUE TITLE
关于Models仓库重构

### ISSUE THREAD

**Issue by rentainhe** [Oneflow-Inc/models#200]
### 重构
目前重构的models仓库代码架构在以下分支，如果有什么更好的修改意见欢迎补充～

https://github.com/Oneflow-Inc/models/tree/rebuild_model_repo

### 后续可能要解决的问题
- README是否需要提供中英文两个版本，目前重构的代码README是写了两个版本，参考[mmclassification](https://github.com/open-mmlab/mmclassification)
- 代码风格不统一，以分类任务为例，由于开发模型的人不同，代码风格不一致，如果不统一一种代码架构，可能会增加后续的维护成本
- 是否需要提供一个统一的documentation，便于使用者快速定位到想用的模型，而不是点进一个个folder里找，但是每个folder都必须提供一个README，方便使用。

**Comment by L1aoXingyu** [comment]
我觉得可以参考 nvidia examples 里面的结构 https://github.com/NVIDIA/DeepLearningExamples

**Comment by MARD1NO** [comment]
一点小建议是：
像quantization，vision这种，最好是开头大写

我现在感觉是，models并不太像一个examples库，我们提供的模型比nvidia的丰富的很多。

可以考虑把支持的模型，在readme中列出来，附上超链接，直接点击就可以找到。

**Comment by rentainhe** [comment]
> 一点小建议是：
> 像quantization，vision这种，最好是开头大写
> 
> 我现在感觉是，models并不太像一个examples库，我们提供的模型比nvidia的丰富的很多。
> 
> 可以考虑把支持的模型，在readme中列出来，附上超链接，直接点击就可以找到。

小写主要是为了统一命名的风格，所以都选择用lower的形式
确实是可以把支持的模型也在readme里列出来，这个修改一下

**Comment by rentainhe** [comment]
> 我觉得可以参考 nvidia examples 里面的结构 https://github.com/NVIDIA/DeepLearningExamples

那是不是可以考虑再额外加一个MODEL_ZOO.md

**Comment by rentainhe** [comment]
Version2: https://github.com/Oneflow-Inc/models/tree/rebuild_model_repo

**Comment by Ldpe2G** [comment]
可以在每个细分任务得根目录下 加个 readme  列出每个模型得超链接，然后主页 readme 每个细分任务直接是 对应 readme 的超链接，这样子可以方便用户快速查找模型

**Comment by rentainhe** [comment]
> 可以在每个细分任务得根目录下 加个 readme 列出每个模型得超链接，然后主页 readme 每个细分任务直接是 对应 readme 的超链接，这样子可以方便用户快速查找模型

额，那就是和第一版一样了，第一版就是这样

**Comment by Ldpe2G** [comment]
> > 可以在每个细分任务得根目录下 加个 readme 列出每个模型得超链接，然后主页 readme 每个细分任务直接是 对应 readme 的超链接，这样子可以方便用户快速查找模型
> 
> 额，那就是和第一版一样了，第一版就是这样

想了下后面会加文档的，文档里再详细列出已经实现的模型，在主页readme哪里加个文档链接就行了

**Comment by rentainhe** [comment]
> > > 可以在每个细分任务得根目录下 加个 readme 列出每个模型得超链接，然后主页 readme 每个细分任务直接是 对应 readme 的超链接，这样子可以方便用户快速查找模型
> > 
> > 
> > 额，那就是和第一版一样了，第一版就是这样
> 
> 想了下后面会加文档的，文档里再详细列出已经实现的模型，在主页readme哪里加个文档链接就行了

额，也可以，文档的话也不是不可以弄，所以主页是只需要一个文档链接？

**Comment by rentainhe** [comment]
暂定方案：
1. 增加documentation，当作一个目录
2. 将原来主页上的readme尽可能减少，但是分级目录里的readme需要补全

**Comment by rentainhe** [comment]
和德澎晟航讨论后最终敲定的方案：
https://github.com/Oneflow-Inc/models
