### ISSUE TITLE
Transformer 使用Graph 能否实现可变的输入句子长度

### ISSUE THREAD

**Issue by 15805383399** [Oneflow-Inc/models#212]
如果使用nn.Graph来搭建模型，必须保证输入数据的 shape是确定的。在一些常见的nlp任务中，训练时可以通过截断以及补零的方式，将所有数据集中的句调整到一致。
## 训练时
但是对于一些长文本的任务（尤其是广义上的长文本，比如一段音乐序列），每个序列的长度会有一个比较大的波动（例如，我正在做的一个项目，序列长度的分布从1000多一直到10000），那么把所有句子padding到同一长度的做法就会使得运算效率变得十分低下。有没有方法可以处理这种情况？
## 推理时
Transformer的decoder部分，在推理时是通过自回归的方式，依次解码出生成序列的。同样的，如果一开始就对生成序列padding到一个最大长度，依然会让计算效率变得十分低下，而且会将生成结果限制最大长度之内，如果达到最大长度时没有输出EOS符，生成结果就是不完整的。有什么方法可以处理这种情况？

**Comment by chengtbf** [comment]
其实这些问题都可以通过 Lazy Actor 支持动态内存池来解决。  😂  但这就涉及到 Regst 生命周期与实际需求不匹配的问题，如 Variable Regst，在其生命周期结束以后仍然有效，即 regst 回收不能释放内存；activation regst 在生命周期结束以后可以回收内存。 这个功能的支持还要改很多地方，一直拖着没去碰（当时最紧急的 GPT 内存问题通过 nccl use compute stream 来解决了）

目前可行的方案：

Train 时:
1. 动态内存问题： 需要依赖编译（第一次  nn.Graph 执行）时提供 max sequence length，推导最大内存（但比如 10000 的 max，序列如果只有 1000，就会非常浪费内存，这个方案可以绕过内存动态分配的问题）；
2. 动态shape问题 与 dynamic batching 问题：同时每次动态推导 shape，根据实际 shape 进行计算，如果一个 batch 涉及到多个 seq 不一样的样例，也需要选择是否要通过 dynamic padding 到当前最大的那个 length（比如 1000， 2000， 2500 三个样例组成一个 mini batch，就需要 padding 到 2500）；或者 for 循环每个 样例单独处理（slice 多个子图分支）。
3. Mirror（纯数据并行）和 Consistent 问题： Lazy Consistent 很难处理 dynamic ，无论是 构图动态、shape 动态、时序动态，都比较难搞（Eager Consistent 可以解决这些问题）。如果上述动态 shape 训练涉及多卡，就需要支持 Graph 的 DDP （工作量也不小） ，如果还是模型并行，就很难受了，dynamic boxing 就很困难，因为涉及到动态切分和拼接 tensor。

推理时：
1. 动态 shape 问题： 这个处理是不是相对简单一些，只需要设置 max length 就行，但是不涉及每次必须 padding 到最大 length 导致计算低效的问题（仍然会浪费内存）
2. length 不设上限的问题： 这个问题还挺棘手的，实际上我们还是最终需要一个上限（就是 batch size = 1，不 OOM 的最大 size），因为超过这个上限，即使只有一个样例也会 OOM 就运行不了了。

**Comment by Ldpe2G** [comment]
或者可以试试这样，一个比较粗暴的方案：

Oneflow 支持从同一个 Module 创建多个训练的 Graph，这些 Graph 共享这个Module 的参数，区别在于 这些 Graph 的区别是输入大小不同。

然后对于变长句子都统一 pad 到最长的固定长度这个问题。

可以采用长度分桶的方法，假设先统计数据集中的长度，然后根据统计数据设置几个长度，接着把句子按照长度分到这些桶中。同一个桶内的句子都 pad 到这个桶的最长长度。

接着对每个桶分别创建一个训练的 Graph 这样。
