### ISSUE TITLE
有关mobilenetv3数据集和精度的问题

### ISSUE THREAD

**Issue by chutianxu** [Oneflow-Inc/models#33]
谢谢你们新开发的MobileNetV3算法~我是天枢项目组成员。

你们提供的imagenette_ofrecord.tar.gz数据集里，似乎只包含train部分。请问能提供一下validation部分的ofrecord格式数据集吗？

另外请问当前mobilenetv3算法的测试集和测试精度，能否提供一下呢？非常感谢。

**Comment by Ldpe2G** [comment]
imagenette_ofrecord.tar.gz 里面包含有训练和验证集的数据

**Comment by Ldpe2G** [comment]
> 另外请问当前mobilenetv3算法的测试集和测试精度，能否提供一下呢？非常感谢。

可以看这个pr:  https://github.com/Oneflow-Inc/models/pull/16

**Comment by chutianxu** [comment]
> > 另外请问当前mobilenetv3算法的测试集和测试精度，能否提供一下呢？非常感谢。
> 
> 可以看这个pr: #16

好的谢谢。

我下载了你们在mobilenetv3文件夹下的imagenette_ofrecord.tar.gz。
https://oneflow-public.oss-cn-beijing.aliyuncs.com/model_zoo/cv/classification/mobilenetv3/mobilenetv3_oneflow_model.tar.gz
但是解压出来只有train一个文件夹。
能否麻烦检查一下~

**Comment by chutianxu** [comment]
> > 另外请问当前mobilenetv3算法的测试集和测试精度，能否提供一下呢？非常感谢。
> 
> 可以看这个pr: #16

好的谢谢。

我下载了你们在mobilenetv3文件夹下提供的imagenette_ofrecord.tar.gz，但是解压出来只有train一个文件夹。
能否麻烦你们检查一下链接~

**Comment by Ldpe2G** [comment]
https://oneflow-public.oss-cn-beijing.aliyuncs.com/datasets/imagenette_ofrecord.tar.gz
 
你是用这个链接吗，我重新下载验证过了，有 train 和 val 两个文件夹
![image](https://user-images.githubusercontent.com/2424744/123074049-8f7d8080-d449-11eb-99bf-2f89a940ee94.png)

**Comment by chutianxu** [comment]
> https://oneflow-public.oss-cn-beijing.aliyuncs.com/datasets/imagenette_ofrecord.tar.gz
> 
> 你是用这个链接吗，我重新下载验证过了，有 train 和 val 两个文件夹
> ![image](https://user-images.githubusercontent.com/2424744/123074049-8f7d8080-d449-11eb-99bf-2f89a940ee94.png)

刚刚去重新下载看了一下，确实是有两个文件夹的。
抱歉可能之前哪里出问题了……
谢谢！
