### ISSUE TITLE
!is_train_job train job must have set state initializer

### ISSUE THREAD

**Issue by WonderingWJ** [Oneflow-Inc/models#380]
运行deepFM的时候出现错误
F20220826 09:06:46.414013 2273878 replace_embedding_ops_pass.cpp:1160] Check failed: !is_train_job train job must have set state initializer
机器环境
A100x8
运行步骤
1. 运行docker oneflowinc/oneflow:nightly-cuda11.2
2. bash train_deepfm.sh

**Comment by liujuncheng** [comment]
非常感谢您的反馈，我们已经复现问题并将在PR https://github.com/Oneflow-Inc/oneflow/pull/9011 中修复，后续我们将向您提供包括修复的安装包，再次感谢您的反馈

**Comment by liujuncheng** [comment]
您好，您可以通过下面命令安装更早的版本使用 one embedding
```
pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112/381fb6c6d4536917dd45fd1f48db12b0514732be
```
我们后续会提供基于修复版本的安装包，再次感谢您的反馈

**Comment by ShiyuanResearch** [comment]
你好，感谢您的反馈，该问题已修复。
修复该问题的pr已合并至master分支，您更新oneflow的nightly版本或者重新拉取nightly的镜像即可。
再次感谢您的反馈。

`python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112 -U`
