### ISSUE TITLE
Default value inconsistent in description

### ISSUE THREAD

**Issue by regnnighe** [Oneflow-Inc/models#389]
As I saw in https://github.com/Oneflow-Inc/models/tree/main/RecommenderSystems/dlrm#arguments-description, the default value for --store_type is cached_ssd, which is different from the setting in https://github.com/Oneflow-Inc/models/blob/main/RecommenderSystems/dlrm/dlrm_train_eval.py.

**Comment by MARD1NO** [comment]
Thanks for your feedback, it has been fixed in https://github.com/Oneflow-Inc/models/pull/390
