### ISSUE TITLE
训练posenet模型报错

### ISSUE THREAD

**Issue by changhuaxu** [Oneflow-Inc/models#80]
![image](https://user-images.githubusercontent.com/80661878/128129157-be538753-66de-49a3-9f01-81fb2b2ce9ef.png)

这个报错是啥情况？

**Comment by Ldpe2G** [comment]
确认下oneflow的版本

**Comment by changhuaxu** [comment]
> 确认下oneflow的版本

oneflow-0.5.0 dev20210803+cu101-cp36-cp36m-manylinux2014_x86_64

**Comment by Ldpe2G** [comment]
我这边用最新的 master 能跑起来，这一行需要在末尾加个 `[0]`
https://github.com/Oneflow-Inc/models/blob/main/poseNet/utils/ofrecord_data_utils.py#L59
